from enum import Enum


class FILE_SOURCE(Enum):
    NOT_FOUND = "NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INVALID_PATH = "INVALID_PATH"
    READ_FAILED = "READ_FAILED"
    WRITE_FAILED = "WRITE_FAILED"
    UNSUPPORTED_TYPE = "UNSUPPORTED_TYPE"
