# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apiserver.v1 import audio_pb2 as apiserver_dot_v1_dot_audio__pb2
from apiserver.v1 import healthz_pb2 as apiserver_dot_v1_dot_healthz__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apiserver/v1/apiserver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FFmpegAudioStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Healthz = channel.unary_unary(
                '/v1.FFmpegAudioStreamService/Healthz',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apiserver_dot_v1_dot_healthz__pb2.HealthzResponse.FromString,
                _registered_method=True)
        self.PushAudioStream = channel.stream_unary(
                '/v1.FFmpegAudioStreamService/PushAudioStream',
                request_serializer=apiserver_dot_v1_dot_audio__pb2.AudioPacket.SerializeToString,
                response_deserializer=apiserver_dot_v1_dot_audio__pb2.AudioStreamResponse.FromString,
                _registered_method=True)
        self.PullAudioStream = channel.unary_stream(
                '/v1.FFmpegAudioStreamService/PullAudioStream',
                request_serializer=apiserver_dot_v1_dot_audio__pb2.StartAudioStreamRequest.SerializeToString,
                response_deserializer=apiserver_dot_v1_dot_audio__pb2.AudioPacket.FromString,
                _registered_method=True)


class FFmpegAudioStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Healthz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushAudioStream(self, request_iterator, context):
        """推送音频流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullAudioStream(self, request, context):
        """拉取音频流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FFmpegAudioStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apiserver_dot_v1_dot_healthz__pb2.HealthzResponse.SerializeToString,
            ),
            'PushAudioStream': grpc.stream_unary_rpc_method_handler(
                    servicer.PushAudioStream,
                    request_deserializer=apiserver_dot_v1_dot_audio__pb2.AudioPacket.FromString,
                    response_serializer=apiserver_dot_v1_dot_audio__pb2.AudioStreamResponse.SerializeToString,
            ),
            'PullAudioStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PullAudioStream,
                    request_deserializer=apiserver_dot_v1_dot_audio__pb2.StartAudioStreamRequest.FromString,
                    response_serializer=apiserver_dot_v1_dot_audio__pb2.AudioPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.FFmpegAudioStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.FFmpegAudioStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FFmpegAudioStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.FFmpegAudioStreamService/Healthz',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apiserver_dot_v1_dot_healthz__pb2.HealthzResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushAudioStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/v1.FFmpegAudioStreamService/PushAudioStream',
            apiserver_dot_v1_dot_audio__pb2.AudioPacket.SerializeToString,
            apiserver_dot_v1_dot_audio__pb2.AudioStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullAudioStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/v1.FFmpegAudioStreamService/PullAudioStream',
            apiserver_dot_v1_dot_audio__pb2.StartAudioStreamRequest.SerializeToString,
            apiserver_dot_v1_dot_audio__pb2.AudioPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
