# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apiserver/v1/apiserver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apiserver/v1/apiserver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from apiserver.v1 import healthz_pb2 as apiserver_dot_v1_dot_healthz__pb2
from apiserver.v1 import audio_pb2 as apiserver_dot_v1_dot_audio__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61piserver/v1/apiserver.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1a\x61piserver/v1/healthz.proto\x1a\x18\x61piserver/v1/audio.proto2\xd4\x01\n\x18\x46\x46mpegAudioStreamService\x12\x36\n\x07Healthz\x12\x16.google.protobuf.Empty\x1a\x13.v1.HealthzResponse\x12=\n\x0fPushAudioStream\x12\x0f.v1.AudioPacket\x1a\x17.v1.AudioStreamResponse(\x01\x12\x41\n\x0fPullAudioStream\x12\x1b.v1.StartAudioStreamRequest\x1a\x0f.v1.AudioPacket0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apiserver.v1.apiserver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FFMPEGAUDIOSTREAMSERVICE']._serialized_start=120
  _globals['_FFMPEGAUDIOSTREAMSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
