# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apiserver/v1/healthz.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apiserver/v1/healthz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61piserver/v1/healthz.proto\x12\x02v1\"X\n\x0fHealthzResponse\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.v1.ServiceStatus\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t*+\n\rServiceStatus\x12\x0b\n\x07Healthy\x10\x00\x12\r\n\tUnhealthy\x10\x01\x42\x38Z6github.com/pachirode/ffmpeg-study/pkg/api/apiserver/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apiserver.v1.healthz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/pachirode/ffmpeg-study/pkg/api/apiserver/v1'
  _globals['_SERVICESTATUS']._serialized_start=124
  _globals['_SERVICESTATUS']._serialized_end=167
  _globals['_HEALTHZRESPONSE']._serialized_start=34
  _globals['_HEALTHZRESPONSE']._serialized_end=122
# @@protoc_insertion_point(module_scope)
