// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: apiserver/v1/apiserver.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FFmpegAudioStreamService_Healthz_FullMethodName         = "/v1.FFmpegAudioStreamService/Healthz"
	FFmpegAudioStreamService_PushAudioStream_FullMethodName = "/v1.FFmpegAudioStreamService/PushAudioStream"
	FFmpegAudioStreamService_PullAudioStream_FullMethodName = "/v1.FFmpegAudioStreamService/PullAudioStream"
)

// FFmpegAudioStreamServiceClient is the client API for FFmpegAudioStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FFmpegAudioStreamServiceClient interface {
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
	// 推送音频流
	PushAudioStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AudioPacket, AudioStreamResponse], error)
	// 拉取音频流
	PullAudioStream(ctx context.Context, in *StartAudioStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioPacket], error)
}

type fFmpegAudioStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFFmpegAudioStreamServiceClient(cc grpc.ClientConnInterface) FFmpegAudioStreamServiceClient {
	return &fFmpegAudioStreamServiceClient{cc}
}

func (c *fFmpegAudioStreamServiceClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, FFmpegAudioStreamService_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegAudioStreamServiceClient) PushAudioStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AudioPacket, AudioStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FFmpegAudioStreamService_ServiceDesc.Streams[0], FFmpegAudioStreamService_PushAudioStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioPacket, AudioStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegAudioStreamService_PushAudioStreamClient = grpc.ClientStreamingClient[AudioPacket, AudioStreamResponse]

func (c *fFmpegAudioStreamServiceClient) PullAudioStream(ctx context.Context, in *StartAudioStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FFmpegAudioStreamService_ServiceDesc.Streams[1], FFmpegAudioStreamService_PullAudioStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartAudioStreamRequest, AudioPacket]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegAudioStreamService_PullAudioStreamClient = grpc.ServerStreamingClient[AudioPacket]

// FFmpegAudioStreamServiceServer is the server API for FFmpegAudioStreamService service.
// All implementations must embed UnimplementedFFmpegAudioStreamServiceServer
// for forward compatibility.
type FFmpegAudioStreamServiceServer interface {
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	// 推送音频流
	PushAudioStream(grpc.ClientStreamingServer[AudioPacket, AudioStreamResponse]) error
	// 拉取音频流
	PullAudioStream(*StartAudioStreamRequest, grpc.ServerStreamingServer[AudioPacket]) error
	mustEmbedUnimplementedFFmpegAudioStreamServiceServer()
}

// UnimplementedFFmpegAudioStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFFmpegAudioStreamServiceServer struct{}

func (UnimplementedFFmpegAudioStreamServiceServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedFFmpegAudioStreamServiceServer) PushAudioStream(grpc.ClientStreamingServer[AudioPacket, AudioStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushAudioStream not implemented")
}
func (UnimplementedFFmpegAudioStreamServiceServer) PullAudioStream(*StartAudioStreamRequest, grpc.ServerStreamingServer[AudioPacket]) error {
	return status.Errorf(codes.Unimplemented, "method PullAudioStream not implemented")
}
func (UnimplementedFFmpegAudioStreamServiceServer) mustEmbedUnimplementedFFmpegAudioStreamServiceServer() {
}
func (UnimplementedFFmpegAudioStreamServiceServer) testEmbeddedByValue() {}

// UnsafeFFmpegAudioStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FFmpegAudioStreamServiceServer will
// result in compilation errors.
type UnsafeFFmpegAudioStreamServiceServer interface {
	mustEmbedUnimplementedFFmpegAudioStreamServiceServer()
}

func RegisterFFmpegAudioStreamServiceServer(s grpc.ServiceRegistrar, srv FFmpegAudioStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedFFmpegAudioStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FFmpegAudioStreamService_ServiceDesc, srv)
}

func _FFmpegAudioStreamService_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegAudioStreamServiceServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegAudioStreamService_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegAudioStreamServiceServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegAudioStreamService_PushAudioStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FFmpegAudioStreamServiceServer).PushAudioStream(&grpc.GenericServerStream[AudioPacket, AudioStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegAudioStreamService_PushAudioStreamServer = grpc.ClientStreamingServer[AudioPacket, AudioStreamResponse]

func _FFmpegAudioStreamService_PullAudioStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartAudioStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FFmpegAudioStreamServiceServer).PullAudioStream(m, &grpc.GenericServerStream[StartAudioStreamRequest, AudioPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegAudioStreamService_PullAudioStreamServer = grpc.ServerStreamingServer[AudioPacket]

// FFmpegAudioStreamService_ServiceDesc is the grpc.ServiceDesc for FFmpegAudioStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FFmpegAudioStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FFmpegAudioStreamService",
	HandlerType: (*FFmpegAudioStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _FFmpegAudioStreamService_Healthz_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushAudioStream",
			Handler:       _FFmpegAudioStreamService_PushAudioStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullAudioStream",
			Handler:       _FFmpegAudioStreamService_PullAudioStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "apiserver/v1/apiserver.proto",
}
