// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *AudioMeta) Default() {
}

func (x *AudioPacket) Default() {
}

func (x *StartAudioStreamRequest) Default() {
}

func (x *AudioStreamResponse) Default() {
}
