// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v6.31.1
// source: apiserver/v1/audio.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 音频流元信息
type AudioMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// codec 编解码器，例如 aac、mp3
	Codec string `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"`
	// sample_rate 采样率
	SampleRate int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// channels 通道数
	Channels int32 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	// pts 当前帧时间戳
	Pts *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=pts,proto3" json:"pts,omitempty"`
}

func (x *AudioMeta) Reset() {
	*x = AudioMeta{}
	mi := &file_apiserver_v1_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMeta) ProtoMessage() {}

func (x *AudioMeta) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioMeta.ProtoReflect.Descriptor instead.
func (*AudioMeta) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_audio_proto_rawDescGZIP(), []int{0}
}

func (x *AudioMeta) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *AudioMeta) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioMeta) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioMeta) GetPts() *timestamppb.Timestamp {
	if x != nil {
		return x.Pts
	}
	return nil
}

// 音频数据包
type AudioPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// meta 音频帧元信息
	Meta *AudioMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// data 编码后的音频帧数据
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// createdAt 当前帧创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *AudioPacket) Reset() {
	*x = AudioPacket{}
	mi := &file_apiserver_v1_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPacket) ProtoMessage() {}

func (x *AudioPacket) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPacket.ProtoReflect.Descriptor instead.
func (*AudioPacket) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_audio_proto_rawDescGZIP(), []int{1}
}

func (x *AudioPacket) GetMeta() *AudioMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AudioPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioPacket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 请求开始音频流
type StartAudioStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// stream_id 唯一流ID
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
}

func (x *StartAudioStreamRequest) Reset() {
	*x = StartAudioStreamRequest{}
	mi := &file_apiserver_v1_audio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAudioStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAudioStreamRequest) ProtoMessage() {}

func (x *StartAudioStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_audio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAudioStreamRequest.ProtoReflect.Descriptor instead.
func (*StartAudioStreamRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_audio_proto_rawDescGZIP(), []int{2}
}

func (x *StartAudioStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// 响应
type AudioStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// success 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message 描述信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AudioStreamResponse) Reset() {
	*x = AudioStreamResponse{}
	mi := &file_apiserver_v1_audio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStreamResponse) ProtoMessage() {}

func (x *AudioStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_audio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStreamResponse.ProtoReflect.Descriptor instead.
func (*AudioStreamResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_audio_proto_rawDescGZIP(), []int{3}
}

func (x *AudioStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AudioStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_apiserver_v1_audio_proto protoreflect.FileDescriptor

var file_apiserver_v1_audio_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x75, 0x64, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8c, 0x01, 0x0a, 0x09, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f,
	0x64, 0x65, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x12, 0x2c, 0x0a, 0x03, 0x70, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x70, 0x74, 0x73, 0x22, 0x7e,
	0x0a, 0x0b, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x21, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x36,
	0x0a, 0x17, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x13, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x61, 0x63, 0x68, 0x69, 0x72, 0x6f, 0x64, 0x65, 0x2f, 0x66, 0x66, 0x6d, 0x70, 0x65, 0x67,
	0x2d, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apiserver_v1_audio_proto_rawDescOnce sync.Once
	file_apiserver_v1_audio_proto_rawDescData = file_apiserver_v1_audio_proto_rawDesc
)

func file_apiserver_v1_audio_proto_rawDescGZIP() []byte {
	file_apiserver_v1_audio_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_audio_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiserver_v1_audio_proto_rawDescData)
	})
	return file_apiserver_v1_audio_proto_rawDescData
}

var file_apiserver_v1_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apiserver_v1_audio_proto_goTypes = []any{
	(*AudioMeta)(nil),               // 0: v1.AudioMeta
	(*AudioPacket)(nil),             // 1: v1.AudioPacket
	(*StartAudioStreamRequest)(nil), // 2: v1.StartAudioStreamRequest
	(*AudioStreamResponse)(nil),     // 3: v1.AudioStreamResponse
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_apiserver_v1_audio_proto_depIdxs = []int32{
	4, // 0: v1.AudioMeta.pts:type_name -> google.protobuf.Timestamp
	0, // 1: v1.AudioPacket.meta:type_name -> v1.AudioMeta
	4, // 2: v1.AudioPacket.createdAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_apiserver_v1_audio_proto_init() }
func file_apiserver_v1_audio_proto_init() {
	if File_apiserver_v1_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiserver_v1_audio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_audio_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_audio_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_audio_proto_msgTypes,
	}.Build()
	File_apiserver_v1_audio_proto = out.File
	file_apiserver_v1_audio_proto_rawDesc = nil
	file_apiserver_v1_audio_proto_goTypes = nil
	file_apiserver_v1_audio_proto_depIdxs = nil
}
